apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mixedconfigs.rabbitmq-admin.io
spec:
  group: rabbitmq-admin.io
  names:
    kind: MixedConfig
    plural: mixedconfigs
    singular: mixedconfig
    shortNames:
      - mc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                globalClustersRefs:
                  type: array
                  description: "References to global clusters"
                  items:
                    type: string
                users:
                  type: array
                  description: "List of RabbitMQ users"
                  items:
                    type: object
                    required:
                      - name
                      - password
                    properties:
                      name:
                        type: string
                        description: "User's name"
                      password:
                        type: string
                        description: "User's password"
                      canLoginWithPassword:
                        type: boolean
                        description: "Whether the user can login with a password"
                        default: true
                      tags:
                        type: string
                        description: "User tags such as Admin, Monitoring, etc."
                        default: ""
                      permissions:
                        type: array
                        description: "List of permissions"
                        items:
                          type: object
                          required:
                            - vhost
                          properties:
                            vhost:
                              type: string
                              description: "The vhost this permission applies to"
                            readRegexp:
                              type: string
                              description: "Read permission regular expression"
                              default: ".*"
                            writeRegexp:
                              type: string
                              description: "Write permission regular expression"
                              default: ".*"
                            configureRegexp:
                              type: string
                              description: "Configure permission regular expression"
                              default: ".*"
                      topicPermissions:
                        type: array
                        description: "List of topic permissions"
                        items:
                          type: object
                          required:
                            - vhost
                          properties:
                            vhost:
                              type: string
                              description: "The vhost this topic permission applies to"
                            exchange:
                              type: string
                              description: "Exchange name"
                            readRegexp:
                              type: string
                              description: "Read permission regular expression for topics"
                              default: ".*"
                            writeRegexp:
                              type: string
                              description: "Write permission regular expression for topics"
                              default: ".*"
                vhosts:
                  type: array
                  description: "List of virtual hosts"
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: "Name of the virtual host"
                      description:
                        type: string
                        description: "Description of the vhost"
                      tags:
                        type: string
                        description: "Tags for the vhost"
                        default: ""
                      defaultQueueType:
                        type: string
                        default: "classic"
                        enum:
                          - classic
                          - quorum
                          - stream
                        description: "Default type of queues in the vhost"
            status:
              type: object
              default: {}
              properties:
                conditions:
                  type: array
                  description: "Array of condition objects"
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastUpdatedTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                  default: []
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
      subresources:
        status: {}
