apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-admin-operator

resources:
- bases/rabbitmq-admin.io-globalconnection.yaml
- bases/rabbitmq-admin.io-mixedconfigs.yaml

- rabbitmq-admin.io-clusterrolebinding.yaml
- rabbitmq-admin.io-namespace.yaml
- rabbitmq-admin.io-role.yaml
- rabbitmq-admin.io-sa.yaml

labels:
- includeSelectors: true
  pairs:
    app: rabbitmq-admin-operator
