apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-admin-operator-role
rules:
  - apiGroups:
      - rabbitmq-admin.io
    resources:
      -
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  #for get connection secret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups:
      - custom.example.com
    resources:
      - mycustomresources/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

#other
  - apiGroups:
      - apps
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
  - apiGroups:
      - ''
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - pods